### ISSUE TITLE
点击授权按钮后，无法正确授权登录

### ISSUE THREAD

**Issue by dbing** [mojisrc/wechat-mini-shop#4]
![image](https://user-images.githubusercontent.com/12548122/50533456-e6e65280-0b64-11e9-9518-856ca46789bf.png)

看提示说，获取 wx.getUserInfo 接口后续将不再出现授权弹窗，请注意升级，
https://developers.weixin.qq.com/community/develop/doc/0000a26e1aca6012e896a517556c01

真机下登录授权调试时出现如下图错误：
![image](https://user-images.githubusercontent.com/12548122/50533734-6840e380-0b6b-11e9-80aa-719a3f9d0aa5.png)

请问该怎么解决呢？

**Comment by hanwenbo** [comment]
@dbing #3 看这个

**Comment by dbing** [comment]
![image](https://user-images.githubusercontent.com/12548122/50556782-6ec08e00-0d18-11e9-989b-56e78d9742ef.png)

我在api 项目中 Conf/config/index.php 添加了如下代码，在小程序中点击去登录，可以看到控制台有打印授权的用户信息，但是还没正确授权成功，错误如下图，

请问我该怎么处理呢？谢谢

![image](https://user-images.githubusercontent.com/12548122/50556799-a9c2c180-0d18-11e9-8f53-a095968a2efa.png)

**Comment by hanwenbo** [comment]
@dbing 文件名改为wechatmini.php

**Comment by dbing** [comment]
@hanwenbo 感谢耐心提供帮助，可以了。谢谢

**Comment by hanwenbo** [comment]
@dbing 不客气 有问题继续
